version: '3.4'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - /home/gustavo/Escritorio/inventario:/var/www/html

  mysql:
    image: mysql:8.2
    container_name: inventory-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_HOST= mysql
      - MYSQL_ROOT_USER= root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DB=inventario
    volumes:
      - .mysql_data:/var/lib/mysql:rw

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: inventory-phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_HOST=mysql